# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Initialize changes_detected Var
  ansible.builtin.set_fact:
    changes_detected_vrfs: false
  delegate_to: localhost

- name: Set file_name Var
  ansible.builtin.set_fact:
    file_name: "{{ MD_Extended.vxlan.fabric.name }}_ndfc_attach_vrfs.yml"
  delegate_to: localhost

- name: Stat Previous File If It Exists
  ansible.builtin.stat:
    path: "{{ role_path }}/files/{{ file_name }}"
  register: data_file_previous
  delegate_to: localhost

- name: Backup Previous Data File If It Exists
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ file_name }}"
    dest: "{{ role_path }}/files/{{ file_name }}.old"
  when: data_file_previous.stat.exists

- name: Delete Previous File If It Exists
  ansible.builtin.file:
    state: absent
    path: "{{ role_path }}/files/{{ file_name }}"
  delegate_to: localhost
  when: data_file_previous.stat.exists

- name: Build VRFs Attach List From Template
  ansible.builtin.template:
    src: ndfc_attach_vrfs.j2
    dest: "{{ role_path }}/files/{{ file_name }}"
  delegate_to: localhost

- name: Create Empty vrf_config Var
  ansible.builtin.set_fact:
    vrf_config: []
  delegate_to: localhost

- name: Set vrf_config Var
  ansible.builtin.set_fact:
    vrf_config: "{{ lookup('file', file_name) | from_yaml }}"
  when: >
    (MD_Extended.vxlan.overlay.vrfs | default([])) | length > 0 or
    (MD_Extended.vxlan.overlay_services.vrfs | default([])) | length > 0
  delegate_to: localhost

- name: Diff Previous and Current Data Files
  cisco.nac_dc_vxlan.dtc.diff_model_changes:
    file_name_previous: "{{ role_path }}/files/{{ file_name }}.old"
    file_name_current: "{{ role_path }}/files/{{ file_name }}"
  register: file_diff_result
  delegate_to: localhost

- name: Set File Change Flag Based on File Diff Result
  ansible.builtin.set_fact:
    changes_detected_vrfs: true
  delegate_to: localhost
  when:
    - file_diff_result.file_data_changed
    - check_roles['save_previous']

- name: Set file_name Var for loopback attachments
  ansible.builtin.set_fact:
    file_name: "{{ MD_Extended.vxlan.fabric.name }}_attach_vrfs_loopbacks.yml"
  delegate_to: localhost

- name: Build VRFs Attach List From Template for loopback
  ansible.builtin.template:
    src: ndfc_attach_vrfs_loopbacks.j2
    dest: "{{ role_path }}/files/{{ file_name }}"
  delegate_to: localhost

- name: Create Empty vrf_config Var
  ansible.builtin.set_fact:
    vrf_attach_config: []
  delegate_to: localhost

- name: Set vrf_config Var
  ansible.builtin.set_fact:
    vrf_attach_config: "{{ lookup('file', file_name) | from_yaml }}"
  when: >
    (MD_Extended.vxlan.overlay.vrfs | default([])) | length > 0 or
    (MD_Extended.vxlan.overlay_services.vrfs | default([])) | length > 0
  delegate_to: localhost