# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Manage Fabric Entry Point
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+     Manage Fabric {{ MD_Extended.vxlan.fabric.name }}"
      - "----------------------------------------------------------------"

- name: Check if fabric MFD {{ MD_Extended.vxlan.fabric.name }} exists in NDFC
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/onemanage/fabrics/{{ MD_Extended.vxlan.fabric.name }}"
  register: get_result
  failed_when: false

- name: Set payload
  set_fact:
    payload:
      templateName: "MSD_Fabric"
      fabricName: "{{ MD_Extended.vxlan.fabric.name }}"
      fabricType: "MFD"
      fabricTechnology: "VXLANFabric"
      nvPairs: "{{ fabric_config }}"

- name: Manage fabric External {{ MD_Extended.vxlan.fabric.name }} in NDFC (PUT)
  cisco.dcnm.dcnm_rest:
    method: PUT
    path: '/appcenter/cisco/ndfc/api/v1/onemanage/fabrics/{{ MD_Extended.vxlan.fabric.name }}'
    json_data: '{{ payload | to_json }}'
  when:
    - get_result.response is defined
    - get_result.response.RETURN_CODE == 200
  register: put_result

- name: Manage fabric External {{ MD_Extended.vxlan.fabric.name }} in NDFC (POST)
  cisco.dcnm.dcnm_rest:
    method: POST
    path: '/appcenter/cisco/ndfc/api/v1/onemanage/fabrics'
    json_data: '{{ payload | to_json }}'
  when: get_result.response is not defined
  register: post_result
