# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Manage VRFs for Federated NDFC
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+     Manage VRFs for Federated Fabrics {{ MD_Extended.vxlan.fabric.name }} and {{ vrf.displayName }} "
      - "----------------------------------------------------------------"
  tags: "{{ nac_tags.create_vrfs_networks }}"
# --------------------------------------------------------------------
# Manage VRF Configuration on NDFC
# --------------------------------------------------------------------

- name: Get existing VRFs in Federated Fabric
  cisco.dcnm.dcnm_rest:
      method: GET
      path: "/appcenter/cisco/ndfc/api/v1/onemanage/top-down/fabrics/{{ MD_Extended.vxlan.fabric.name }}/vrfs"
  register: dcnm_vrf_existing
  tags: "{{ nac_tags.create_vrfs_networks }}"

- name: Check if VRF Exists
  set_fact:
    vrf_exist_result: "{{ dcnm_vrf_existing | json_query(vrf_query) }}"
  vars:
    vrf_query: "response.DATA[?vrfName=='{{vrf.displayName}}'].vrfName"
  tags: "{{ nac_tags.create_vrfs_networks }}"

- name: Update VRF for Federated NDFCs
  cisco.dcnm.dcnm_rest:
    path: "/appcenter/cisco/ndfc/api/v1/onemanage/top-down/fabrics/{{ MD_Extended.vxlan.fabric.name }}/vrfs/{{ vrf.displayName }}"
    method: "PUT"
    json_data: "{{ vrf | to_json}}"
  when: vrf_exist_result|default(None)|length != 0
  tags: "{{ nac_tags.create_vrfs_networks }}"

- name: Configure VRF for Federated NDFCs
  cisco.dcnm.dcnm_rest:
    path: "/appcenter/cisco/ndfc/api/v1/onemanage/top-down/fabrics/{{ MD_Extended.vxlan.fabric.name }}/vrfs"
    method: "POST"
    json_data: "{{ vrf | to_json}}"
  when: vrf_exist_result|default(None)|length == 0
  tags: "{{ nac_tags.create_vrfs_networks }}"