# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---
- name: Manage VRFs and Networks for MFD Entry Point
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+     Manage VRFs and Networks MFD Fabric {{ MD_Extended.vxlan.fabric.name }}"
      - "----------------------------------------------------------------"

# --------------------------------------------------------------------
# Manage VRF Configuration for Federated NDFCs
# --------------------------------------------------------------------

- name: Set filename for federated
  ansible.builtin.set_fact:
    file_name: "ndfc_fed_attach_vrfs.yml"
  when:
    - MD.vxlan.multisite.overlay.vrfs is defined
    - changes_detected_vrfs
    - MD.vxlan.fabric.type == 'MFD'

- name: Load VRF federated details from file
  ansible.builtin.set_fact:
    fed_vrf_config: "{{ lookup('file', role_path + '/../common/files/mfd/{{ MD_Extended.vxlan.fabric.name }}/' + file_name) | from_json }}"
  when:
    - MD.vxlan.multisite.overlay.vrfs is defined
    - changes_detected_vrfs
    - MD.vxlan.fabric.type == 'MFD'

- name: Get existing VRFs in Federated Fabric
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/onemanage/top-down/fabrics/{{ MD.vxlan.fabric.name }}/vrfs"
  register: dcnm_vrf_existing
  when:
    - MD.vxlan.multisite.overlay.vrfs is defined
    - changes_detected_vrfs
    - MD.vxlan.fabric.type == 'MFD'

- name: Manage NDFC Fabric VRFs for Federated
  ansible.builtin.include_tasks: vrf_fed_config.yml
  loop: "{{ fed_vrf_config }}"
  loop_control:
    loop_var: vrf
  when:
    - MD.vxlan.multisite.overlay.vrfs is defined
    - changes_detected_vrfs
    - MD.vxlan.fabric.type == 'MFD'

# --------------------------------------------------------------------
# Manage Loopback VRF attachments on NDFC (MFD)
# --------------------------------------------------------------------
- name: Attach VRF Loopbacks per VRF
  ansible.builtin.include_tasks: vrf_loopbacks.yml
  loop_control:
    loop_var: vrf
  loop: "{{ MD.vxlan.multisite.overlay.vrfs }}"
  when:
    - MD.vxlan.multisite.overlay.vrfs is defined
    - MD.vxlan.fabric.type == 'MFD'

- name: Get vrf attachments list
  cisco.dcnm.dcnm_rest:
    method: GET
    path: /appcenter/cisco/ndfc/api/v1/onemanage/top-down/fabrics/{{ MD_Extended.vxlan.fabric.name }}/vrfs/attachments
  register: vrfAttachmentList

- name: Filter vrf attachments to be removed
  cisco.nac_dc_vxlan.dtc.fed_overlay_check:
    model_data: "{{ MD_Extended }}"
    ndfc_data: "{{ switch_list_create.response.DATA }}"
    ndfc_attachment_data: "{{ vrfAttachmentList.response.DATA }}"
    check_type: "vrf_attach"
  register: not_required_vrfs

- name: Remove vrf attachments
  cisco.dcnm.dcnm_rest:
    method: POST
    path: /appcenter/cisco/ndfc/api/v1/onemanage/top-down/fabrics/{{ MD_Extended.vxlan.fabric.name }}/vrfs/attachments
    json_data: "{{ not_required_vrfs.attachments_payload | to_json }}"
  register: vrf_attachment_result

- name: Manage NDFC Child Fabric VRFs
  cisco.nac_dc_vxlan.dtc.manage_child_fabric_vrfs:
    nd_version: "{{ nd_version }}"
    msite_data: "{{ MD_Multisite }}"
    fabric_type: "{{ MD_Extended.vxlan.fabric.type }}"
  register: child_fabric_vrf_results

# --------------------------------------------------------------------
# Manage Network Configuration for Federated NDFCs
# --------------------------------------------------------------------
- name: Query existing network.switches_to_attach.split in Federated Fabric
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/onemanage/top-down/fabrics/{{ MD.vxlan.fabric.name }}/networks"
  register: fed_networks_existing
  when:
    - MD.vxlan.multisite.overlay.networks is defined
    - changes_detected_networks
    - MD.vxlan.fabric.type == 'MFD'

- name: Manage NDFC Fabric Networks for Federated
  ansible.builtin.include_tasks: network_fed_config.yml
  loop: "{{ net_config }}"
  loop_control:
    loop_var: network
  when:
    - MD.vxlan.fabric.type == 'MFD'
    - MD.vxlan.multisite.overlay.networks is defined
    - changes_detected_networks

- name: Attach switches for all networks
  cisco.dcnm.dcnm_rest:
    path: "/appcenter/cisco/ndfc/api/v1/onemanage/top-down/fabrics/networks/attachments"
    method: "POST"
    json_data: "{{ network_switches | to_json }}"
  when:
    - network_switches is defined
    - MD.vxlan.fabric.type == 'MFD'
    - MD.vxlan.multisite.overlay.networks is defined
    - changes_detected_networks

- name: Attach network to switches and ports for all networks
  cisco.dcnm.dcnm_rest:
    path: "/appcenter/cisco/ndfc/api/v1/onemanage/top-down/fabrics/networks/multiattach"
    method: "POST"
    json_data: "{{ network_switches_ports | to_json }}"
  when:
    - network_switches_ports is defined
    - MD.vxlan.fabric.type == 'MFD'
    - MD.vxlan.multisite.overlay.networks is defined
    - changes_detected_networks

- name: Get network attachments list
  cisco.dcnm.dcnm_rest:
    method: GET
    path: /appcenter/cisco/ndfc/api/v1/onemanage/top-down/fabrics/{{ MD_Extended.vxlan.fabric.name }}/networks/attachments
  register: networkAttachmentList
  when:
    - MD.vxlan.fabric.type == 'MFD'
    - MD.vxlan.multisite.overlay.networks is defined
    - changes_detected_networks

- name: Filter network attachments to be removed
  cisco.nac_dc_vxlan.dtc.fed_overlay_check:
    model_data: "{{ MD_Extended }}"
    ndfc_data: "{{ switch_list_create.response.DATA }}"
    ndfc_attachment_data: "{{ networkAttachmentList.response.DATA }}"
    check_type: "network_attach"
  register: network_attachments_payload
  when:
    - MD.vxlan.fabric.type == 'MFD'
    - MD.vxlan.multisite.overlay.networks is defined
    - changes_detected_networks

- name: Attach network to switches and ports for all networks
  cisco.dcnm.dcnm_rest:
    method: POST
    path: /appcenter/cisco/ndfc/api/v1/onemanage/top-down/fabrics/{{ MD_Extended.vxlan.fabric.name }}/networks/attachments
    json_data: "{{ network_attachments_payload.attachments_payload | to_json }}"
  when:
    - network_switches_ports is defined
    - MD.vxlan.fabric.type == 'MFD'
    - MD.vxlan.multisite.overlay.networks is defined
    - changes_detected_networks

- name: Manage NDFC Child Fabric Networks
  cisco.nac_dc_vxlan.dtc.manage_child_fabric_networks:
    nd_version: "{{ nd_version }}"
    msite_data: "{{ MD_Multisite }}"
    fabric_type: "{{ MD_Extended.vxlan.fabric.type }}"
  register: child_fabric_network_results
