# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---
- name: Initialize changes_detected Var
  ansible.builtin.set_fact:
    changes_detected_networks: false
  delegate_to: localhost

- name: Set file_name Var
  ansible.builtin.set_fact:
    file_name: "ndfc_attach_networks.yml"
  delegate_to: localhost

- name: Stat Previous File If It Exists
  ansible.builtin.stat:
    path: "{{ path_name }}{{ file_name }}"
  register: data_file_previous
  delegate_to: localhost

- name: Backup Previous Data File If It Exists
  ansible.builtin.copy:
    src: "{{ path_name }}{{ file_name }}"
    dest: "{{ path_name }}{{ file_name }}.old"
  when: data_file_previous.stat.exists

- name: Delete Previous Data File If It Exists
  ansible.builtin.file:
    state: absent
    path: "{{ path_name }}{{ file_name }}"
  delegate_to: localhost
  when: data_file_previous.stat.exists

- name: Build Networks Attach List From Template
  ansible.builtin.template:
    src: "{{ role_path }}/../common/templates/ndfc_attach_networks.j2"
    dest: "{{ path_name }}{{ file_name }}"
    mode: '0644'
  delegate_to: localhost

- name: Set net_config Var
  ansible.builtin.set_fact:
    net_config: []
  delegate_to: localhost

- name: Set net_config Var
  ansible.builtin.set_fact:
    net_config: "{{ lookup('file', path_name + file_name) | from_yaml }}"
  when: (MD_Extended.vxlan.multisite.overlay.networks | default([])) | length > 0
  delegate_to: localhost

- name: Diff Previous and Current Data Files
  cisco.nac_dc_vxlan.dtc.diff_model_changes:
    file_name_previous: "{{ path_name }}{{ file_name }}.old"
    file_name_current: "{{ path_name }}{{ file_name }}"
  register: file_diff_result
  delegate_to: localhost

- name: Set File Change Flag Based on File Diff Result
  ansible.builtin.set_fact:
    changes_detected_networks: true
  delegate_to: localhost
  when:
    - file_diff_result.file_data_changed
    - check_roles['save_previous']

- name: Set file_name Var for switches and port attachments
  ansible.builtin.set_fact:
    file_name: "ndfc_attach_network_switches_ports.yml"
    file_name2: "ndfc_attach_network_switches.yml"
    switches: []
    networks: []
  delegate_to: localhost

- name: Build VRFs Attach List for switches From Template
  ansible.builtin.template:
    src: "{{ role_path }}/../common/templates/ndfc_networks/mfd_fabric/ndfc_attach_networks_switches.j2"
    dest: "{{ path_name }}{{ file_name }}"
    mode: '0644'
  delegate_to: localhost

- name: Build VRFs Attach List for switches and ports From Template
  ansible.builtin.template:
    src: "{{ role_path }}/../common/templates/ndfc_networks/mfd_fabric/ndfc_attach_networks_switches_ports.j2"
    dest: "{{ path_name }}{{ file_name2 }}"
    mode: '0644'
  delegate_to: localhost

# - name: Build Network attach list for switches on Federated
#   ansible.builtin.template:
#     src: ndfc_attach_networks_switches_fed.j2
#     dest: "{{ path_name }}{{ file_name }}"
#   delegate_to: localhost

# - name: Build Network attach list for switches and ports on Federated
#   ansible.builtin.template:
#     src: ndfc_attach_networks_switches_ports_fed.j2
#     dest: "{{ path_name }}{{ file_name2 }}"
#   delegate_to: localhost

- name: Set network_switches Var
  ansible.builtin.set_fact:
    network_switches: "{{ lookup('file', path_name + file_name) | from_yaml }}"
    network_switches_ports: "{{ lookup('file', path_name + file_name2) | from_yaml }}"
  when: (MD_Extended.vxlan.overlay.networks | default([])) | length > 0
  delegate_to: localhost
