# Copyright (c) 2025 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Set file_name Var
  ansible.builtin.set_fact:
    file_name: "ndfc_vpc_domain_id_resource.yml"
  delegate_to: localhost

- name: Stat Previous File If It Exists
  ansible.builtin.stat:
    path: "{{ path_name }}{{ file_name }}"
  register: data_file_previous
  delegate_to: localhost

- name: Backup Previous Data File If It Exists
  ansible.builtin.copy:
    src: "{{ path_name }}{{ file_name }}"
    dest: "{{ path_name }}{{ file_name }}.old"
    mode: preserve
  when: data_file_previous.stat.exists

- name: Delete Previous Data File If It Exists
  ansible.builtin.file:
    state: absent
    path: "{{ path_name }}{{ file_name }}"
  delegate_to: localhost
  when: data_file_previous.stat.exists

- name: Build vPC Domain ID Resource
  ansible.builtin.template:
    src: ndfc_vpc/ndfc_vpc_domain_id_resource.j2
    dest: "{{ path_name }}{{ file_name }}"
    mode: '0644'
  delegate_to: localhost

- name: Set vpc_domain Var default
  ansible.builtin.set_fact:
    vpc_domain_id_resource: []
  delegate_to: localhost

- name: Set vpc_domain_id_resource Var
  ansible.builtin.set_fact:
    vpc_domain_id_resource: "{{ lookup('file', path_name + file_name) | from_yaml }}"
  when: data_model_extended.vxlan.topology.vpc_peers | length > 0
  delegate_to: localhost

- name: Build vPC Domain ID Diff Between Previous and Current Run
  # This task must be run before the next task because
  # dtc.diff_model_changes deletes the .old file if it exists
  cisco.nac_dc_vxlan.dtc.diff_compare:
    old_file: "{{ path_name }}{{ file_name }}.old"
    new_file: "{{ path_name }}{{ file_name }}"
  register: vpc_domain_id_resource_diff_result
  delegate_to: localhost

- name: Get MD5 Diff Previous and Current Data Files
  cisco.nac_dc_vxlan.dtc.diff_model_changes:
    file_name_previous: "{{ path_name }}{{ file_name }}.old"
    file_name_current: "{{ path_name }}{{ file_name }}"
  register: file_diff_result
  delegate_to: localhost

- name: Set File Change Flag Based on File Diff Result
  cisco.nac_dc_vxlan.common.change_flag_manager:
    fabric_type: "{{ data_model_extended.vxlan.fabric.type }}"
    fabric_name: "{{ data_model_extended.vxlan.fabric.name }}"
    role_path: "{{ common_role_path }}"
    operation: update
    change_flag: changes_detected_vpc_domain_id_resource
    flag_value: true
  delegate_to: localhost
  when:
    - file_diff_result.file_data_changed
    - check_roles['save_previous']
