# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---
factory_defaults:
  vxlan:
    global:
      ebgp:
        bgp_asn_mode: Multi-AS
        leaf_same_bgp_asn: 
      ibgp:
        tcam_allocation: true
        enable_mvpn_vri_id_range: true
        enable_l3_vni_no_vlan: false
      route_reflectors: 2
      anycast_gateway_mac: 20:20:00:00:00:aa
      auth_proto: MD5
      enable_nxapi_http: false
      nxapi_http_port: 80
      enable_nxapi_https: true
      nxapi_https_port: 443
      layer2_vni_range:
        from: 30000
        to: 49000
      layer3_vni_range:
        from: 50000
        to: 59000
      layer2_vlan_range:
        from: 2300
        to: 2999
      layer3_vlan_range:
        from: 2000
        to: 2299
      vpc:
        peer_link_vlan: 3600
        peer_keep_alive: management
        auto_recovery_time: 360
        delay_restore_time: 150
        peer_link_port_channel_id: 500
        ipv6_nd_sync: true
        advertise_pip: false
        advertise_pip_border_only: true
        domain_id_range: 1-1000
        fabric_vpc_qos: false
        fabric_vpc_qos_policy_name: spine_qos_for_fabric_vpc_peering
      spanning_tree:
        root_bridge_protocol: unmanaged
        vlan_range:
          - from: 1
            to: 3967
        mst_instance_range:
          - from: 0
        bridge_priority: 0
      netflow:
        enable: false
      ptp:
        enable: false
        domain_id: 0
        lb_id: 0
      snmp_server_host_trap: true
      bootstrap:
        enable_bootstrap: false
        enable_local_dhcp_server: false
        enable_cdp_mgmt: false
    topology:
      switches:
        routing_loopback_id: 0
        vtep_loopback_id: 1
        interface_breakouts:
          module: 1
          from: 1
          to: 1
          map: '10g-4x'
          enable_during_bootstrap: false
        interfaces:
          topology_switch_access_interface:
            description: "NetAsCode Access Interface"
            mtu: jumbo
            speed: auto
            enabled: true
            access_vlan: 1
            spanning_tree_portfast: true
            enable_bpdu_guard: true
            duplex: auto
            orphan_port: false
          topology_switch_dot1q_interface:
            description: "NetAsCode Dot1q Interface"
            mtu: jumbo
            speed: auto
            enabled: true
            access_vlan: 1
            spanning_tree_portfast: true
            enable_bpdu_guard: true
            duplex: auto
            orphan_port: false
          topology_switch_trunk_interface:
            description: "NetAsCode Trunk Interface"
            mtu: jumbo
            speed: auto
            enabled: true
            trunk_allowed_vlans: none
            spanning_tree_portfast: true
            enable_bpdu_guard: true
            duplex: auto
            orphan_port: false
            native_vlan: ""
          topology_switch_access_po_interface:
            description: "NetAsCode Access PO Interface"
            mtu: jumbo
            speed: auto
            enabled: true
            access_vlan: 1
            pc_mode: active
            spanning_tree_portfast: true
            enable_bpdu_guard: true
            duplex: auto
            orphan_port: false
          topology_switch_trunk_po_interface:
            description: "NetAsCode Trunk PO Interface"
            mtu: jumbo
            speed: auto
            enabled: true
            trunk_allowed_vlans: none
            pc_mode: active
            spanning_tree_portfast: true
            enable_bpdu_guard: true
            duplex: auto
            orphan_port: false
            native_vlan: ""
          topology_switch_routed_interface:
            description: "NetAsCode Routed Interface"
            mtu: 9216
            speed: auto
            enabled: true
          topology_switch_routed_sub_interface:
            description: "NetAsCode Routed Sub Interface"
            mtu: 9216
            speed: auto
            enabled: true
          topology_switch_routed_po_interface:
            description: "NetAsCode Routed PO Interface"
            mtu: 9216
            speed: auto
            enabled: true
            pc_mode: active
          topology_switch_loopback_interface:
            description: "NetAsCode Loopback Interface"
            enabled: true
        poap:
          bootstrap: false
      vpc_peers:
        domain_id: 1
      fabric_links:
        mtu: 9216
        admin_state: true
      edge_connections:
    underlay:
      general:
        routing_protocol: ospf
        enable_ipv6_underlay: false
        replication_mode: multicast
        manual_underlay_allocation: false
        underlay_routing_loopback_id: 0
        underlay_vtep_loopback_id: 1
        underlay_routing_protocol_tag: UNDERLAY
        underlay_rp_loopback_id: 254
        intra_fabric_interface_mtu: 9216
        layer2_host_interface_mtu: 9216
        unshut_host_interfaces: true
      ipv4:
        fabric_interface_numbering: p2p
        subnet_mask: 30
        underlay_routing_loopback_ip_range: 10.2.0.0/22
        underlay_vtep_loopback_ip_range: 10.3.0.0/22
        underlay_rp_loopback_ip_range: 10.254.254.0/24
        underlay_subnet_ip_range: 10.4.0.0/16
      ipv6:
        enable_ipv6_link_local_address: true
        underlay_subnet_mask: 126
        underlay_routing_loopback_ip_range: fd00::a02:0/119
        underlay_vtep_loopback_ip_range: fd00::a03:0/118
        underlay_rp_loopback_ip_range: fd00::254:254:0/118
        underlay_subnet_ip_range: fd00::a04:0/112
      ospf:
        area_id: 0.0.0.0
        authentication_enable: false
        authentication_key_id: 127
      isis:
        level: level-2
        net_area_number: "0001"
        network_point_to_point: true
        authentication_enable: false
        authentication_key_id: 127
        overload_bit: true
        overload_bit_elapsed_time: 60
      bgp:
        authentication_enable: false
        authentication_key_type: 3
        max_paths: 4  # Review
      multicast:
        rendezvous_points: 2
        rp_mode: asm
        underlay_rp_loopback_id: 254
        ipv4:
          group_subnet: 239.1.1.0/25
          authentication_enable: false
          trm_enable: false
          trm_default_group: 239.1.1.0
        ipv6:
          group_subnet: ff1e::/121
          trmv6_enable: false
          trmv6_default_group: "ff1e::"   # Quote due to ending in colon to avoid YAML error
        underlay_primary_rp_loopback_id: 2
        underlay_backup_rp_loopback_id: 3
        underlay_second_backup_rp_loopback_id: 4
        underlay_third_backup_rp_loopback_id: 5
      bfd:
        enable: false
        ibgp: false
        ospf: false
        pim: false
        isis: false
        authentication_enable: false
        authentication_key_id: 100
    overlay:
      vrfs:
        vrf_description: "Configured by Ansible NetAsCode"
        vrf_intf_desc: "Configured by Ansible NetAsCode"
        vrf_int_mtu: 9216
        loopback_route_tag: 12345
        max_bgp_paths: 1
        max_ibgp_paths: 2
        ipv6_linklocal_enable: true
        # Staging ipv6 route-map attribute for later usage after low-level collection adds support.
        # ipv6_redist_direct_routemap: FABRIC-RMAP-REDIST-SUBNET
        adv_host_routes: false
        adv_default_routes: true
        static_default_route: true
        disable_rt_auto: false
        netflow_enable: false
        no_rp: false
        rp_external: false
        redist_direct_routemap: FABRIC-RMAP-REDIST-SUBNET
        trm_enable: false
        trm_bgw_msite: false
        # Staging trmv6 attributes for later usage after low-level collection adds support.
        # trmv6_no_rp: false
        # trmv6_rp_external: false
        # trmv6_enable: false
      networks:
        net_description: "Configured by Ansible NetAsCode"
        is_l2_only: false
        arp_supress: false
        l3gw_on_border: false
        mtu_l3intf: 9216
        multicast_group_address: 239.1.1.1
        netflow_enable: false
        route_target_both: false
        route_tag: 12345
        trm_enable: false
        # Staging trmv6 attribute for later usage after low-level collection adds support.
        # trmv6_enable: false
      vrf_attach_groups:
        switches: []
      network_attach_groups:
        switches: []
    policy:
      template_name: switch_freeform
      priority: 500
    overlay_extensions:
      vrf_lites:
        ospf:
          areas:
            area_type: standard
          default_area: 0
          distance: 110
          bfd:
            enabled: false
          default_information_originate:
            always: false
          nssa:
            default_information_originate: false
            no_redistribution: false
            no_summary: false
            translate:
              always: false
              supress_fa: false
              never: false
        bgp:
          best_path_as_path_relax: false
          graceful_restart: true
          graceful_restart_helper: false
          address_family_ipv4_unicast:
            additional_paths_receive: false
            additional_paths_send: false
            default_originate: false
            ebgp_distance: 20
            ibgp_distance: 200
            local_distance: 220
          address_family_ipv6_unicast:
            additional_paths_receive: false
            additional_paths_send: false
            default_originate: false
            ebgp_distance: 20
            ibgp_distance: 200
            local_distance: 220
        switches:
          interfaces:
            ospf:
              auth_type: none
              auth_key_id: 0
              cost: 1
              passive_interface: false
              mtu_ignore: false
              advertise_subnet: false
              bfd:
                enabled: false
              hello_interval: 10
              dead_interval: 40
              network_type: broadcast
              priority: 1
              lsa_retransmit_interval: 5
              lsa_transmit_delay: 1
          bgp_peers:
            next_hop_self: false
            bfd:
              enabled: false
            disable_connected_check: false
            remove_private_as: false
            remove_private_as_all: false
            address_family_ipv4_unicast:
              send_community: false
              send_ext_community: false
              allow_as_in: false
              allow_as_in_number: 3
              as_override: false
              route_reflector_client: false
              default_originate: false
              next_hop_self: false
            address_family_ipv6_unicast:
              send_community: false
              send_ext_community: false
              allow_as_in: false
              allow_as_in_number: 3
              as_override: false
              route_reflector_client: false
              default_originate: false
              next_hop_self: false
    multisite:
      layer2_vni_range:
        from: 30000
        to: 49000
      layer3_vni_range:
        from: 50000
        to: 59000
      enable_ipv6_underlay: false
      anycast_gateway_mac: 20:20:00:00:00:aa
      vtep_loopback_id: 100
      bgw_ip_tag: 54321
      ipv4_vtep_loopback_range: 10.10.0.0/24
      ipv6_vtep_loopback_range: fd00::a10:0/120
      overlay_dci:
        deployment_method: Direct_To_BGWS
        route_server:
          redistribute_direct: false
          ip_tag: 54321
        ipv4_dci_subnet_range: 10.10.1.0/24
        ipv4_dci_subnet_mask: 30
        ipv6_dci_subnet_range: fd00::a11:0/120
        ipv6_dci_subnet_mask: 126
        underlay_autoconfig: true
        enable_bgp_send_community: false
        enable_bgp_log_neighbor_change: false
        enable_bgp_bfd: false
        delay_restore: 300
        enable_ebgp_password: false
        enable_trm: false
      isn:
        sub_int_range: 2-511
        enable_nxapi_http: false
        nxapi_http_port: 80
        enable_nxapi_https: true
        nxapi_https_port: 443
        bootstrap:
          enable_bootstrap: false
          enable_local_dhcp_server: false
