- ansible.builtin.set_fact:
    fabric_file_name: "{{ MD.fabric.global.name }}_create_fabric.yml"

- name: Build Fabric Creation Parameters From Template
  template:
    src: create_fabric.j2
    dest: "{{ role_path }}/files/{{ fabric_file_name }}"

# - ansible.builtin.set_fact:
#     fabric_config: []

- ansible.builtin.set_fact:
    fabric_config: "{{ lookup('file', fabric_file_name) | from_yaml }}"
  when: MD.fabric.global