---
- name: Set interface_access_po_file_name Var
  ansible.builtin.set_fact:
    interface_access_po_file_name: "{{ MD.fabric.global.name }}_interface_access_po.yml"

- name: Build Interface
  ansible.builtin.template:
    src: interface_access_po.j2
    dest: "{{ role_path }}/files/{{ interface_access_po_file_name }}"

- name: Set interface_access_po Var
  ansible.builtin.set_fact:
    interface_access_po: []

- name: Set interface_access_po Var
  ansible.builtin.set_fact:
    interface_access_po: "{{ lookup('file', interface_access_po_file_name) | from_yaml }}"