---
- name: Set interface_routed_file_name Var
  ansible.builtin.set_fact:
    interface_routed_file_name: "{{ MD.fabric.global.name }}_interface_routed.yml"

- name: Build Interface
  ansible.builtin.template:
    src: interface_routed.j2
    dest: "{{ role_path }}/files/{{ interface_routed_file_name }}"

- name: Set interface_routed Var default
  ansible.builtin.set_fact:
    interface_routed: []

- name: Set interface_routed Var
  ansible.builtin.set_fact:
    interface_routed: "{{ lookup('file', interface_routed_file_name) | from_yaml }}"