# Copyright (c) 2025 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- ansible.builtin.fail: msg="Service Model Not Defined.  Role cisco.nac_dc_vxlan.validate Must Be Called First"
  when: MD is undefined
  delegate_to: localhost

# --------------------------------------------------------------------
# Remove all files from the previous run if run_map requires it
# --------------------------------------------------------------------
- name: Set path_name Var
  ansible.builtin.set_fact:
    path_name: "{{ role_path }}/files/ebgp_vxlan/{{ MD_Extended.vxlan.fabric.name }}/"
  delegate_to: localhost

- name: Cleanup Files from Previous Run if run_map requires it
  ansible.builtin.import_tasks: cleanup_files.yml
  when:
    - not run_map_read_result.diff_run or ((force_run_all is defined) and (force_run_all is true|bool))

# --------------------------------------------------------------------
# Build Create Fabric parameter List From Template
# --------------------------------------------------------------------

- name: Build Fabric Create Parameters
  ansible.builtin.import_tasks: common/ndfc_fabric.yml

# --------------------------------------------------------------------
# Build NDFC Fabric Switch Inventory List From Template
# --------------------------------------------------------------------

- name: Build NDFC Fabric Switch Inventory List From Template
  ansible.builtin.import_tasks: common/ndfc_inventory.yml

# We need to also build an inventory list without bootstrap settings
# This will be used for device removal.
- name: Build NDFC Fabric Switch Inventory List From Template - No Bootstrap
  ansible.builtin.import_tasks: common/ndfc_inventory_no_bootstrap.yml

# --------------------------------------------------------------------
# Build vPC Domain ID Resource From Template
# --------------------------------------------------------------------

- name: Build vPC Domain ID Resource From Template
  ansible.builtin.import_tasks: common/ndfc_vpc_domain_id_resource.yml

# --------------------------------------------------------------------
# Build vPC Intra Fabric Links for vPC Peering From Template
# --------------------------------------------------------------------

- name: Build vPC Intra Fabric Links From Template
  ansible.builtin.import_tasks: common/ndfc_vpc_fabric_peering_links.yml

# --------------------------------------------------------------------
# Build vPC Peering parameter List From Template
# --------------------------------------------------------------------

- name: Build vPC Peering Parameters
  ansible.builtin.import_tasks: common/ndfc_vpc_peering_pairs.yml

# ## --------------------------------------------------------------------
# ## Build NDFC Fabric VRFs Attach List From Template
# ## --------------------------------------------------------------------
# #
# #- name: Build NDFC Fabric VRFs Attach List From Template
# #  ansible.builtin.import_tasks: vxlan/ndfc_vrfs.yml
# #
# ## --------------------------------------------------------------------
# ## Build NDFC Fabric Networks Attach List From Template
# ## --------------------------------------------------------------------
# #
# #- name: Build NDFC Fabric Networks Attach List From Template
# #  ansible.builtin.import_tasks: vxlan/ndfc_networks.yml
# #
# # --------------------------------------------------------------------
# # Build NDFC Fabric Loopback Interfaces List From Template
# # --------------------------------------------------------------------

# - name: Build NDFC Fabric Loopback Interfaces List From Template
#   ansible.builtin.import_tasks: common/ndfc_interface_loopback.yml

# # --------------------------------------------------------------------
# # Build NDFC Fabric Access Port-Channel Interfaces List From Template
# # --------------------------------------------------------------------

# - name: Build NDFC Fabric Access Port-Channel Interfaces List From Template
#   ansible.builtin.import_tasks: common/ndfc_interface_access_po.yml

# # --------------------------------------------------------------------
# # Build NDFC Fabric Trunk Port-Channel Interfaces List From Template
# # --------------------------------------------------------------------

# - name: Build NDFC Fabric Trunk Port-Channel Interfaces List From Template
#   ansible.builtin.import_tasks: common/ndfc_interface_trunk_po.yml

# # --------------------------------------------------------------------
# # Build NDFC Fabric Interface Routed List From Template
# # --------------------------------------------------------------------

# - name: Build NDFC Fabric Interface Routed List From Template
#   ansible.builtin.import_tasks: common/ndfc_interface_routed.yml

# # --------------------------------------------------------------------
# # Build NDFC Fabric Sub-Interface Routed List From Template
# # --------------------------------------------------------------------

# - name: Build NDFC Fabric Sub-Interface Routed List From Template
#   ansible.builtin.import_tasks: common/ndfc_sub_interface_routed.yml

# # --------------------------------------------------------------------
# # Build NDFC Fabric Routed Port-Channel Interface List From Template
# # --------------------------------------------------------------------

# - name: Build NDFC Fabric Routed Port-Channel Interface List From Template
#   ansible.builtin.import_tasks: common/ndfc_interface_po_routed.yml

# # --------------------------------------------------------------------
# # Build Trunk Interfaces List From Template
# # --------------------------------------------------------------------

# - name: Build Trunk Interfaces List From Template
#   ansible.builtin.import_tasks: common/ndfc_interface_trunk.yml

# # --------------------------------------------------------------------
# # Build Access Interfaces List From Template
# # --------------------------------------------------------------------

# - name: Build Access Interfaces List From Template
#   ansible.builtin.import_tasks: common/ndfc_interface_access.yml

# --------------------------------------------------------------------
# Build Fabric Interface vPC List From Template
# --------------------------------------------------------------------

- name: Build Fabric interface vPC List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_vpc.yml

# # --------------------------------------------------------------------
# # Build Fabric interface all List From Template
# # --------------------------------------------------------------------

# - name: Build Fabric interface All List From Template
#   ansible.builtin.import_tasks: common/ndfc_interface_all.yml

# --------------------------------------------------------------------
# Build Fabric Policy List From Template
# --------------------------------------------------------------------

- name: Build Fabric Policy List From Template
  ansible.builtin.import_tasks: common/ndfc_policy.yml

# # --------------------------------------------------------------------
# # Build Fabric Links List From Template
# # --------------------------------------------------------------------

# - name: Build Fabric Links List From Template
#   ansible.builtin.import_tasks: common/ndfc_fabric_links.yml

# # --------------------------------------------------------------------
# # Build Edge Connections List From Template
# # --------------------------------------------------------------------

# - name: Edge Connections List From Template
#   ansible.builtin.import_tasks: common/ndfc_edge_connections.yml

# --------------------------------------------------------------------
# Save Local Variables To NameSpace Dict For Use Elsewhere
# --------------------------------------------------------------------
- name: Save Local Variables With Namespace Context
  ansible.builtin.set_fact:
    vars_common_ebgp_vxlan:
        changes_detected_fabric: "{{ changes_detected_fabric }}"
        changes_detected_fabric_links: false
#         changes_detected_fabric_links: "{{ changes_detected_fabric_links }}"
#         changes_detected_edge_connections: "{{ changes_detected_edge_connections }}"
#         changes_detected_interface_access_po: "{{ changes_detected_interface_access_po }}"
#         changes_detected_interface_access: "{{ changes_detected_interface_access }}"
#         changes_detected_interfaces: "{{ changes_detected_interfaces }}"
#         changes_detected_interface_loopback: "{{ changes_detected_interface_loopback }}"
#         changes_detected_interface_po_routed: "{{ changes_detected_interface_po_routed }}"
#         changes_detected_interface_routed: "{{ changes_detected_interface_routed }}"
#         changes_detected_interface_trunk_po: "{{ changes_detected_interface_trunk_po }}"
#         changes_detected_interface_trunk: "{{ changes_detected_interface_trunk }}"
        changes_detected_interface_vpc: "{{ changes_detected_interface_vpc }}"
        changes_detected_inventory: "{{ changes_detected_inventory }}"
        changes_detected_link_vpc_peering: "{{ changes_detected_link_vpc_peering }}"
# #        changes_detected_networks: "{{ changes_detected_networks }}"
        changes_detected_policy: "{{ changes_detected_policy }}"
#         changes_detected_sub_interface_routed: "{{ changes_detected_sub_interface_routed }}"
        changes_detected_vpc_peering: "{{ changes_detected_vpc_peering }}"
        changes_detected_vpc_domain_id_resource: "{{ changes_detected_vpc_domain_id_resource }}"
# #        changes_detected_vrfs: "{{ changes_detected_vrfs }}"
        fabric_config: "{{ fabric_config }}"
#         fabric_links: "{{ fabric_links }}"
#         edge_connections: "{{ edge_connections }}"
#         interface_access_po: "{{ interface_access_po }}"
#         interface_access: "{{ interface_access }}"
#         interface_all: "{{ interface_all }}"
#         int_loopback_config: "{{ int_loopback_config }}"
#         interface_po_routed: "{{ interface_po_routed }}"
#         interface_routed: "{{ interface_routed }}"
#         interface_trunk_po: "{{ interface_trunk_po }}"
#         interface_trunk: "{{ interface_trunk }}"
        interface_vpc: "{{ interface_vpc }}"
        inv_config: "{{ inv_config }}"
        link_vpc_peering: "{{ link_vpc_peering }}"
# #        net_config: "{{ net_config }}"
        poap_data: "{{ poap_data }}"
        policy_config: "{{ policy_config }}"
#         sub_interface_routed: "{{ sub_interface_routed }}"
        updated_inv_config: "{{ updated_inv_config }}"
        updated_inv_config_no_bootstrap: "{{ updated_inv_config_no_bootstrap }}"
        vpc_peering: "{{ vpc_peering }}"
        vpc_domain_id_resource: "{{ vpc_domain_id_resource }}"
# #        vrf_config: "{{ vrf_config }}"
# #        vrf_attach_config: "{{ vrf_attach_config }}"

- name: Run Diff Flags
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+     Fabric Changes Detected -               [ {{ vars_common_ebgp_vxlan.changes_detected_fabric }} ]"
      - "+     Inventory Changes Detected -            [ {{ vars_common_ebgp_vxlan.changes_detected_inventory }} ]"
      - "+     vPC Link Peer Changes Detected -        [ {{ vars_common_ebgp_vxlan.changes_detected_link_vpc_peering }} ]"
      - "+     vPC Peer Changes Detected -             [ {{ vars_common_ebgp_vxlan.changes_detected_vpc_peering }} ]"
      - "+     vPC Domain ID Detected -                [ {{ vars_common_ebgp_vxlan.changes_detected_vpc_domain_id_resource }} ]"
      - "+     ----- Interfaces -----"
      - "+     Interface vPC Changes Detected -        [ {{ vars_common_ebgp_vxlan.changes_detected_interface_vpc }} ]"
#       - "+     Interface Access Changes Detected -     [ {{ vars_common_ebgp_vxlan.changes_detected_interface_access }} ]"
#       - "+     Interface Access PO Changes Detected -  [ {{ vars_common_ebgp_vxlan.changes_detected_interface_access_po }} ]"
#       - "+     Interface Loopback Changes Detected -   [ {{ vars_common_ebgp_vxlan.changes_detected_interface_loopback }} ]"
#       - "+     Interface PO Routed Changes Detected -  [ {{ vars_common_ebgp_vxlan.changes_detected_interface_po_routed }} ]"
#       - "+     Interface Routed Changes Detected -     [ {{ vars_common_ebgp_vxlan.changes_detected_interface_routed }} ]"
#       - "+     Interface Trunk Changes Detected -      [ {{ vars_common_ebgp_vxlan.changes_detected_interface_trunk }} ]"
#       - "+     Interface Trunk PO Changes Detected -   [ {{ vars_common_ebgp_vxlan.changes_detected_interface_trunk_po }} ]"
#       - "+     Sub Interface Routed Changes Detected - [ {{ vars_common_ebgp_vxlan.changes_detected_sub_interface_routed }} ]"
#       - "+     ----- All Interfaces -----"
#       - "+     All Interfaces Changes Detected -       [ {{ vars_common_ebgp_vxlan.changes_detected_interfaces }} ]"
#       - "+     ----- All Interfaces -----"
# #      - "+     VRFs Changes Detected -                 [ {{ vars_common_ebgp_vxlan.changes_detected_vrfs }} ]"
# #      - "+     Networks Changes Detected -             [ {{ vars_common_ebgp_vxlan.changes_detected_networks }} ]"
      - "+     Policy Changes Detected -               [ {{ vars_common_ebgp_vxlan.changes_detected_policy }} ]"
#       - "+     Fabric Links Changes Detected -         [ {{ vars_common_ebgp_vxlan.changes_detected_fabric_links }} ]"
#       - "+     Edge Connections Changes Detected -     [ {{ vars_common_ebgp_vxlan.changes_detected_edge_connections }} ]"
      - "+     ----- Run Map -----"
      - "+     Run Map Diff Run -                      [ {{ run_map_read_result.diff_run }} ]"
      - "+     Force Run Flag  -                       [ {{ force_run_all }} ]"
      - "----------------------------------------------------------------"
