# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Fail if Data Model is not defined
  ansible.builtin.fail:
    msg: "Service Model Not Defined. Role cisco.nac_dc_vxlan.validate Must Be Called First"
  when: MD is undefined
  delegate_to: localhost

# ------------------------------------------------------------------------
# Remove all files from the previous run if run_map requires it
# ------------------------------------------------------------------------
- name: Set path_name Var
  ansible.builtin.set_fact:
    path_name: "{{ role_path }}/files/isn/{{ MD_Extended.vxlan.fabric.name }}/"
  delegate_to: localhost

- name: Cleanup Files from Previous Run if run_map requires it
  ansible.builtin.import_tasks: cleanup_files.yml
  when:
    - not run_map_read_result.diff_run or ((force_run_all is defined) and (force_run_all is true|bool))

# ------------------------------------------------------------------------
# Build ISN Fabric List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric List From Template
  ansible.builtin.import_tasks: common/ndfc_fabric.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Switch Inventory List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Switch Inventory List From Template
  ansible.builtin.import_tasks: common/ndfc_inventory.yml

# We need to also build an inventory list without bootstrap settings
# This will be used for device removal.
- name: Build ISN Fabric Switch Inventory List From Template - No Bootstrap
  ansible.builtin.import_tasks: common/ndfc_inventory_no_bootstrap.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Breakout Interfaces List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Breakout Interfaces List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_breakout.yml

# ------------------------------------------------------------------------
# Build iBGP VXLAN Fabric PreProv Breakout Interfaces List From Template
# ------------------------------------------------------------------------

- name: Build iBGP VXLAN Fabric Breakout PreProv Interfaces List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_breakout_preprov.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Loopback Interfaces List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Loopback Interfaces List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_loopback.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Access Port-Channel Interfaces List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Access Port-Channel Interfaces List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_access_po.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Trunk Port-Channel Interfaces List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Trunk Port-Channel Interfaces List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_trunk_po.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Interface Routed List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Interface Routed List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_routed.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Sub-Interface Routed List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Sub-Interface Routed List From Template
  ansible.builtin.import_tasks: common/ndfc_sub_interface_routed.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Routed Port-Channel Interface List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Routed Port-Channel Interface List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_po_routed.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Trunk Interfaces List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Trunk Interfaces List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_trunk.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Access Interfaces List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Access Interfaces List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_access.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Dot1q Interfaces List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Dot1q Interfaces List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_dot1q.yml

# ------------------------------------------------------------------------
# Build ISN Fabric vPC Interface List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric vPC Interface List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_vpc.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Interface All List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Interface All List From Template
  ansible.builtin.import_tasks: common/ndfc_interface_all.yml

# ------------------------------------------------------------------------
# Build ISN Fabric Policy List From Template
# ------------------------------------------------------------------------

- name: Build ISN Fabric Policy List From Template
  ansible.builtin.import_tasks: common/ndfc_policy.yml

# ------------------------------------------------------------------------
# Build ISN Edge Connections List From Template
# ------------------------------------------------------------------------

- name: Build ISN Edge Connections List From Template
  ansible.builtin.import_tasks: common/ndfc_edge_connections.yml

# ------------------------------------------------------------------------
# Save Local Variables To NameSpace Dict For Use Elsewhere
# ------------------------------------------------------------------------
- name: Save Local Variables With Namespace Context
  ansible.builtin.set_fact:
    vars_common_isn:
      fabric_config: "{{ fabric_config }}"
      interface_breakout: "{{ interface_breakout }}"
      interface_breakout_preprov: "{{ interface_breakout_preprov }}"
      interface_access_po: "{{ interface_access_po }}"
      interface_access: "{{ interface_access }}"
      interface_all_create: "{{ interface_all_create }}"
      interface_all_remove_overridden: "{{ interface_all_remove_overridden }}"
      interface_diff_result: "{{ interface_diff_result }}"
      int_loopback_config: "{{ int_loopback_config }}"
      interface_po_routed: "{{ interface_po_routed }}"
      interface_routed: "{{ interface_routed }}"
      interface_trunk_po: "{{ interface_trunk_po }}"
      interface_trunk: "{{ interface_trunk }}"
      interface_vpc: "{{ interface_vpc }}"
      interface_dot1q: "{{ interface_dot1q }}"
      inv_config: "{{ inv_config }}"
      poap_data: "{{ poap_data }}"
      policy_config: "{{ policy_config }}"
      sub_interface_routed: "{{ sub_interface_routed }}"
      updated_inv_config: "{{ updated_inv_config }}"
      updated_inv_config_no_bootstrap: "{{ updated_inv_config_no_bootstrap }}"
