# Copyright (c) 2025 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT
---

- name: Role Entry Point - [cisco.nac_dc_vxlan.dtc.remove]
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+     Calling Role - [cisco.nac_dc_vxlan.dtc.remove]           +"
      - "----------------------------------------------------------------"
  tags: "{{ nac_tags.remove }}" # Tags defined in roles/common_global/vars/main.yml

- name: Display Device Configuration Method
  ansible.builtin.debug:
    msg: "Configuring NXOS Devices using Nexus Dashboard (Direct to Controller)"
  tags: "{{ nac_tags.remove }}"

- name: Get List of eBGP VXLAN Fabric Switches from Nexus Dashboard
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ data_model_extended.vxlan.fabric.name }}/inventory/switchesByFabric"
  register: switch_list
  tags: "{{ nac_tags.remove }}"

- name: Remove eBGP VXLAN Fabric vPC Peering
  ansible.builtin.import_tasks: common/vpc_peers.yml
  tags: "{{ nac_tags.remove_vpc_peers }}"
  when:
    - change_flags.changes_detected_vpc_peering

- name: Remove eBGP VXLAN Fabric ToR Pairing from Nexus Dashboard
  ansible.builtin.import_tasks: common/tor_pairing.yml
  tags: "{{ nac_tags.remove_tor_pairing }}"
  when:
    - vars_common_ebgp_vxlan is defined
    - vars_common_ebgp_vxlan.changes_detected_tor_pairing

- name: Remove eBGP VXLAN Fabric Policy from Nexus Dashboard
  ansible.builtin.import_tasks: common/policy.yml
  tags: "{{ nac_tags.remove_policy }}"
  when:
    - change_flags.changes_detected_policy

- name: Remove eBGP VXLAN Fabric Interfaces from Nexus Dashboard
  ansible.builtin.import_tasks: common/interfaces.yml
  tags: "{{ nac_tags.remove_interfaces }}"
  when:
    - change_flags.changes_detected_interfaces

- name: Remove eBGP VXLAN Fabric Networks from Nexus Dashboard
  ansible.builtin.import_tasks: common_vxlan/networks.yml
  tags: "{{ nac_tags.remove_networks }}"
  when:
    - change_flags.changes_detected_networks

- name: Remove eBGP VXLAN Fabric VRFs from Nexus Dashboard
  ansible.builtin.import_tasks: common_vxlan/vrfs.yml
  tags: "{{ nac_tags.remove_vrfs }}"
  when:
    - change_flags.changes_detected_vrfs

- name: Remove eBGP VXLAN Fabric Switches from Nexus Dashboard
  ansible.builtin.import_tasks: common/switches.yml
  tags: "{{ nac_tags.remove_switches }}"
  when:
    - change_flags.changes_detected_inventory
