---
- name: Set vars_common Based On Fabric Type - VXLAN_EVPN/iBGP_VXLAN
  ansible.builtin.set_fact:
    vars_common_local: "{{ vars_common_vxlan }}"
  when: MD_Extended.vxlan.fabric.type == "VXLAN_EVPN"

- name: Set vars_common Based On Fabric Type - eBGP_VXLAN
  ansible.builtin.set_fact:
    vars_common_local: "{{ vars_common_ebgp_vxlan }}"
  when: MD_Extended.vxlan.fabric.type == "eBGP_VXLAN"

- name: Process TOR pairing creates
  cisco.nac_dc_vxlan.dtc.process_tor_pairing:
    tor_pairing: "{{ vars_common_local.tor_pairing }}"
    fabric_name: "{{ MD_Extended.vxlan.fabric.name }}"
  register: tor_create_operations
  delegate_to: localhost
  when:
    - vars_common_local.changes_detected_tor_pairing | default(false)

- name: Pair ToR switches in Nexus Dashboard
# Move that task to "Process TOR pairing creates", call API call from Python module
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "{{ item.path }}"
    json_data: "{{ item.payload | to_json }}"
  loop: "{{ tor_create_operations.create_operations | default([]) }}"
  loop_control:
    label: "{{ item.pairing_id }}"
  when:
    - vars_common_local.changes_detected_tor_pairing | default(false)
    - tor_create_operations.create_operations is defined
    - tor_create_operations.create_operations | length > 0

