# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Role Entry Point - [cisco.nac_dc_vxlan.dtc.create]
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+     Calling Role - [cisco.nac_dc_vxlan.dtc.create]           +"
      - "----------------------------------------------------------------"
  tags: "{{ nac_tags.create }}" # Tags defined in roles/common_global/vars/main.yml

- name: Display Device Configuration Method
  ansible.builtin.debug:
    msg: "Configuring NXOS Devices using NDFC (Direct to Controller)"
  tags: "{{ nac_tags.create }}"

- name: Create NDFC VXLAN Fabric
  ansible.builtin.import_tasks: common/fabric.yml
  when:
    - MD_Extended.vxlan.fabric.name is defined
    - MD_Extended.vxlan.fabric.type == "VXLAN_EVPN"
    - MD_Extended.vxlan.global is defined
    - vars_common_vxlan.changes_detected_fabric
  tags: "{{ nac_tags.create_fabric }}"

- name: Manage NDFC VXLAN Fabric Switches
  ansible.builtin.import_tasks: common/devices.yml
  when:
    - MD_Extended.vxlan.topology.switches | length > 0
    - vars_common_vxlan.changes_detected_inventory
  tags: "{{ nac_tags.create_switches }}"

- name: Manage NDFC VXLAN vPC Peering
  ansible.builtin.import_tasks: common/vpc_peering.yml
  when:
    - MD_Extended.vxlan.topology.vpc_peers | length > 0
    - vars_common_vxlan.changes_detected_vpc_peering
  tags: "{{ nac_tags.create_vpc_peers }}"

- name: Config-Save block to propagate vPC changes to the fabric
  block:
    - name: Config-Save for Fabric {{ MD_Extended.vxlan.fabric.name }}
      cisco.dcnm.dcnm_rest:
        method: POST
        path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ MD_Extended.vxlan.fabric.name }}/config-save"
      when: MD_Extended.vxlan.topology.switches | length > 0
      register: config_save
      # TODO: Need to add logic to only save if changes are made

  rescue:
    - name: Config-Save for Fabric {{ MD_Extended.vxlan.fabric.name }} - Failed
      ansible.builtin.debug:
        msg: "{{ config_save.msg.DATA }}"


- name: Manage NDFC VXLAN Fabric Interfaces
  ansible.builtin.import_tasks: common/interfaces.yml
  when:
    - (MD_Extended.vxlan.topology.interfaces.modes.all.count >0) and (MD_Extended.vxlan.topology.switches | length > 0)
    - vars_common_vxlan.changes_detected_interfaces
  tags: "{{ nac_tags.create_interfaces }}"

- name: Manage NDFC Fabric Inter Links
  ansible.builtin.import_tasks: common/edge_connections.yml
  when:
    - MD_Extended.vxlan.topology.edge_connections | length > 0
    - changes_detected_edge_connections
  tags: "{{ nac_tags.create_links }}"


- name: Manage NDFC VXLAN Fabric VRFs and Networks
  ansible.builtin.import_tasks: vxlan/vrfs_networks.yml
  when:
    - MD_Extended.vxlan.overlay is defined
    - MD_Extended.vxlan.topology.switches | length > 0
    - vars_common_vxlan.changes_detected_vrfs or vars_common_vxlan.changes_detected_networks
  tags: "{{ nac_tags.create_vrfs_networks }}"

- name: Manage NDFC VXLAN Fabric Intra Links
  ansible.builtin.import_tasks: common/links.yml
  when:
    - MD_Extended.vxlan.topology.fabric_links | length > 0
    - vars_common_vxlan.changes_detected_fabric_links
  tags: "{{ nac_tags.create_links }}"

- name: Manage NDFC VXLAN Fabric Policies
  ansible.builtin.import_tasks: common/policies.yml
  when:
    - (MD_Extended.vxlan.policy is defined) and (MD_Extended.vxlan.policy.policies | length > 0)
    - vars_common_vxlan.changes_detected_policy
  tags: "{{ nac_tags.create_policy }}"
