# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Role Entry Point - [cisco.nac_dc_vxlan.dtc.create]
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+     Calling Role - [cisco.nac_dc_vxlan.dtc.create]           +"
      - "----------------------------------------------------------------"
  tags: "{{ nac_tags.create }}" # Tags defined in roles/common_global/vars/main.yml

- name: Display Device Configuration Method
  ansible.builtin.debug:
    msg: "Configuring NXOS Devices using Nexus Dashboard (Direct to Controller)"
  tags: "{{ nac_tags.create }}"

- name: Create ISN Fabric in Nexus Dashboard
  ansible.builtin.import_tasks: isn/fabric.yml
  when:
    - data_model_extended.vxlan.fabric.name is defined
    - data_model_extended.vxlan.fabric.type == "ISN"
    - data_model_extended.vxlan.multisite is defined
    - change_flags.changes_detected_fabric
  tags: "{{ nac_tags.create_fabric }}"

- name: Manage ISN Fabric Switches in Nexus Dashboard
  ansible.builtin.import_tasks: common/devices.yml
  when:
    - data_model_extended.vxlan.topology.switches | length > 0
    - change_flags.changes_detected_inventory
  tags: "{{ nac_tags.create_switches }}"

- name: Manage ISN Fabric Inter Links in Nexus Dashboard
  ansible.builtin.import_tasks: common/edge_connections.yml
  when:
    - data_model_extended.vxlan.topology.edge_connections | length > 0
    - change_flags.changes_detected_edge_connections
  tags: "{{ nac_tags.create_links }}"

- name: Manage ISN Fabric Interfaces in Nexus Dashboard
  ansible.builtin.import_tasks: common/interfaces.yml
  when:
    - (data_model_extended.vxlan.topology.interfaces.modes.all.count >0) and (data_model_extended.vxlan.topology.switches | length > 0)
    - change_flags.changes_detected_interfaces
  tags: "{{ nac_tags.create_interfaces }}"

- name: Manage ISN Fabric Policies in Nexus Dashboard
  ansible.builtin.import_tasks: common/policies.yml
  when:
    - (data_model_extended.vxlan.policy is defined) and (data_model_extended.vxlan.policy.policies | length > 0)
    - change_flags.changes_detected_policy
  tags: "{{ nac_tags.create_policy }}"
