# Copyright (c) 2026 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Manage MCFG Child Fabrics Entry Point
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+     Manage Fabric {{ data_model_extended.vxlan.fabric.name }} Child Fabrics"
      - "----------------------------------------------------------------"

- name: Run dtc.common.tasks.mcfg.ndfc_child_fabrics.yml
  ansible.builtin.import_tasks: "{{ role_path }}/../common/tasks/mcfg/ndfc_child_fabrics.yml"

- name: Add Child Fabrics To MCFG Fabric in Nexus Dashboard
  cisco.nac_dc_vxlan.dtc.manage_child_fabrics:
    parent_fabric: "{{ data_model_extended.vxlan.fabric.name }}"
    parent_fabric_type: "{{ data_model_extended.vxlan.fabric.type }}"
    child_fabrics: "{{ data_model_mcfg_child_fabrics.to_be_added }}"
    state: present

- name: Config-Save Block to Propagate Child Fabrics in MCFG Fabric in Nexus Dashboard
  block:
    - name: Config-Save for MCFG Fabric in Nexus Dashboard
      cisco.dcnm.dcnm_rest:
        method: POST
        path: "/onemanage/appcenter/cisco/ndfc/api/v1/onemanage/fabrics/{{ data_model_extended.vxlan.fabric.name }}/config-save"
      register: config_save

  rescue:
    - name: Config-Save for MCFG Fabric in Nexus Dashboard - Failed
      ansible.builtin.debug:
        msg: "{{ config_save.msg.DATA }}"
      when:
        - config_save.msg.RETURN_CODE is defined
        - config_save.msg.RETURN_CODE == 500
